#version: '3.8'
 
services:
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    restart: always
    ports:
      - "3001:3306"  # 映射到主服务器的端口
    volumes:
      - ./master/data:/var/lib/mysql  # 挂载数据目录
      - ./master/config/mysql.conf:/etc/mysql/conf.d/mysql.conf  # 挂载主服务器的配置文件
      - ./master/log:/var/log/mysql  # 挂载日志目录
      #- ./mysql/init:/docker-entrypoint-initdb.d/    #/docker-entrypoint-initdb.d/这是数据库提供的初始化目录，数据库在启动时会默认执行当期目录下的以.sql或者.sh结尾的文件。
    environment:
      - LANG=C.UTF-8                                #设置容器编码
      - TZ=Asia/Shanghai                            #设置容器时区与宿主机保持一致
      - MYSQL_ROOT_PASSWORD=root                  #设置数据库密码
      - MYSQL_DATABASE=nacos                  #设置数据库名称
      - MYSQL_USER=admin                            #设置数据库用户名
      - MYSQL_PASSWORD=admin                         #设置数据库密码
      - MYSQL_ALLOW_EMPTY_PASSWORD=false            #设置是否允许空密码
    command: --lower-case-table-names=1 --server-id=1 --log-bin=master-bin --binlog-do-db=nacos --binlog-format=row --gtid-mode=ON --enforce-gtid-consistency=ON  # 主服务器的命令参数
 
  mysql-slave:
    image: mysql:5.7
    container_name: mysql-slave
    restart: always
    ports:
      - "3002:3306"  # 映射到从服务器的端口
    volumes:
      - ./slave/data:/var/lib/mysql  # 挂载数据目录
      - ./slave/config:/etc/mysql/conf.d  # 挂载从服务器的配置文件
      - ./slave/log:/var/log/mysql  # 挂载日志目录
      #- ./mysql/init:/docker-entrypoint-initdb.d/    #/docker-entrypoint-initdb.d/这是数据库提供的初始化目录，数据库在启动时会默认执行当期目录下的以.sql或者.sh结尾的文件。
    environment:
      - LANG=C.UTF-8                                #设置容器编码
      - TZ=Asia/Shanghai                            #设置容器时区与宿主机保持一致
      - MYSQL_ROOT_PASSWORD=root                  #设置数据库密码
      - MYSQL_DATABASE=nacos                  #设置数据库名称
      - MYSQL_USER=admin                            #设置数据库用户名
      - MYSQL_PASSWORD=admin                         #设置数据库密码
      - MYSQL_ALLOW_EMPTY_PASSWORD=false            #设置是否允许空密码
    command: --lower-case-table-names=1 --server-id=2 --log-bin=slave-bin --binlog-do-db=nacos --binlog-format=row --gtid-mode=ON --enforce-gtid-consistency=ON --skip-slave-start  # 从服务器的命令参数
    depends_on:
      - mysql-master  # 确保主服务器先启动
