version: '3.6'
name: gitlab
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: '127.0.0.1'
    privileged: true
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1:30080' # web站点访问地址
        registry_external_url 'http://127.0.0.1:30080'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
      GITLAB_ROOT_PASSWORD: 'abc123456'
    ports:
      - '30080:30080' # 注意宿主机和容器内部的端口要一致，否则external_url无法访问
      - '443:443'
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    user: root
    restart: always
    ports:
      - 8080:8080
      - 5000:5000
    volumes:
      - ./jenkins/jenkins_home/:/var/jenkins_home

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - postgres
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=Sonar12#$
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=Sonar12#$
      - POSTGRES_DB=sonarqube
    volumes:
      - ./postgres/postgresql:/var/lib/postgresql
      - ./postgres/postgresql_data:/var/lib/postgresql/data

networks:
  gitlab:
    external: true
