spring:
  profiles:
    active: dev
  port: 8080
  freemarker:
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    template-loader-path: classpath:/templates/
#  jackson:
#    property-naming-strategy: SNAKE_CASE
server:
  port: 8080
  error:
    path: /error
nacos:
  config:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: nacos

logging:
  level:
    root: info
