spring:
  profiles:
    active: dev
  port: 8080
server:
  port: 8080
  error:
    path: /error
nacos:
  config:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: nacos

logging:
  level:
    root: info
