#version: '3.8'
services:
  rmqname:
    image: apache/rocketmq:5.2.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    restart: always
    privileged: true
    volumes:
      - ./rocketmq/nameserver/logs:/home/rocketmq/logs
      - ./rocketmq/nameserver/bin/runserver.sh:/home/rocketmq/rocketmq-5.2.0/bin/runserver.sh
    environment:
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=256M
    command: ["sh","mqnamesrv"]
    networks:
      - rocketmq
  broker:
    image: apache/rocketmq:5.2.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    restart: always
    privileged: true
    volumes:
      - ./rocketmq/broker/logs:/home/rocketmq/logs
      - ./rocketmq/broker/store:/home/rocketmq/stores
      - ./rocketmq/broker/conf/broker.conf:/home/rocketmq/broker.conf
      - ./rocketmq/broker/bin/runbroker.sh:/home/rocketmq/rocketmq-5.2.0/bin/runbroker.sh
    depends_on:
      - 'rmqname'
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=512M
    command: ["sh","mqbroker","-c","/home/rocketmq/broker.conf"]
    networks:
      - rocketmq
  rmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - 7897:8080
    restart: always
    privileged: true
    depends_on:
      - rmqname
    environment:
      - JAVA_OPTS= -Xmx256M -Xms256M -Xmn128M -Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks:
      - rocketmq
networks:
  rocketmq:
    external: true

